// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.34.2
// 	protoc        v5.28.2
// source: internal/shell/parser/zu/zu.proto

package zu

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Zu struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Entries []*ZuEntry `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
}

func (x *Zu) Reset() {
	*x = Zu{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_shell_parser_zu_zu_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Zu) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Zu) ProtoMessage() {}

func (x *Zu) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shell_parser_zu_zu_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Zu.ProtoReflect.Descriptor instead.
func (*Zu) Descriptor() ([]byte, []int) {
	return file_internal_shell_parser_zu_zu_proto_rawDescGZIP(), []int{0}
}

func (x *Zu) GetEntries() []*ZuEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type ZuEntry struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Path        string `protobuf:"bytes,1,opt,name=path,proto3" json:"path,omitempty"`
	AccessCount int64  `protobuf:"varint,2,opt,name=accessCount,proto3" json:"accessCount,omitempty"`
}

func (x *ZuEntry) Reset() {
	*x = ZuEntry{}
	if protoimpl.UnsafeEnabled {
		mi := &file_internal_shell_parser_zu_zu_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *ZuEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZuEntry) ProtoMessage() {}

func (x *ZuEntry) ProtoReflect() protoreflect.Message {
	mi := &file_internal_shell_parser_zu_zu_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZuEntry.ProtoReflect.Descriptor instead.
func (*ZuEntry) Descriptor() ([]byte, []int) {
	return file_internal_shell_parser_zu_zu_proto_rawDescGZIP(), []int{0, 0}
}

func (x *ZuEntry) GetPath() string {
	if x != nil {
		return x.Path
	}
	return ""
}

func (x *ZuEntry) GetAccessCount() int64 {
	if x != nil {
		return x.AccessCount
	}
	return 0
}

var File_internal_shell_parser_zu_zu_proto protoreflect.FileDescriptor

var file_internal_shell_parser_zu_zu_proto_rawDesc = []byte{
	0x0a, 0x21, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c, 0x2f, 0x73, 0x68, 0x65, 0x6c, 0x6c,
	0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x7a, 0x75, 0x2f, 0x7a, 0x75, 0x2e, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x12, 0x02, 0x7a, 0x75, 0x22, 0x6b, 0x0a, 0x02, 0x7a, 0x75, 0x12, 0x26, 0x0a,
	0x07, 0x65, 0x6e, 0x74, 0x72, 0x69, 0x65, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x0c,
	0x2e, 0x7a, 0x75, 0x2e, 0x7a, 0x75, 0x2e, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x52, 0x07, 0x65, 0x6e,
	0x74, 0x72, 0x69, 0x65, 0x73, 0x1a, 0x3d, 0x0a, 0x05, 0x65, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x12,
	0x0a, 0x04, 0x70, 0x61, 0x74, 0x68, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x70, 0x61,
	0x74, 0x68, 0x12, 0x20, 0x0a, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43, 0x6f, 0x75, 0x6e,
	0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0b, 0x61, 0x63, 0x63, 0x65, 0x73, 0x73, 0x43,
	0x6f, 0x75, 0x6e, 0x74, 0x42, 0x1a, 0x5a, 0x18, 0x69, 0x6e, 0x74, 0x65, 0x72, 0x6e, 0x61, 0x6c,
	0x2f, 0x73, 0x68, 0x65, 0x6c, 0x6c, 0x2f, 0x70, 0x61, 0x72, 0x73, 0x65, 0x72, 0x2f, 0x7a, 0x75,
	0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_internal_shell_parser_zu_zu_proto_rawDescOnce sync.Once
	file_internal_shell_parser_zu_zu_proto_rawDescData = file_internal_shell_parser_zu_zu_proto_rawDesc
)

func file_internal_shell_parser_zu_zu_proto_rawDescGZIP() []byte {
	file_internal_shell_parser_zu_zu_proto_rawDescOnce.Do(func() {
		file_internal_shell_parser_zu_zu_proto_rawDescData = protoimpl.X.CompressGZIP(file_internal_shell_parser_zu_zu_proto_rawDescData)
	})
	return file_internal_shell_parser_zu_zu_proto_rawDescData
}

var file_internal_shell_parser_zu_zu_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_shell_parser_zu_zu_proto_goTypes = []any{
	(*Zu)(nil),      // 0: zu.zu
	(*ZuEntry)(nil), // 1: zu.zu.entry
}
var file_internal_shell_parser_zu_zu_proto_depIdxs = []int32{
	1, // 0: zu.zu.entries:type_name -> zu.zu.entry
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_internal_shell_parser_zu_zu_proto_init() }
func file_internal_shell_parser_zu_zu_proto_init() {
	if File_internal_shell_parser_zu_zu_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_internal_shell_parser_zu_zu_proto_msgTypes[0].Exporter = func(v any, i int) any {
			switch v := v.(*Zu); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_internal_shell_parser_zu_zu_proto_msgTypes[1].Exporter = func(v any, i int) any {
			switch v := v.(*ZuEntry); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_internal_shell_parser_zu_zu_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_internal_shell_parser_zu_zu_proto_goTypes,
		DependencyIndexes: file_internal_shell_parser_zu_zu_proto_depIdxs,
		MessageInfos:      file_internal_shell_parser_zu_zu_proto_msgTypes,
	}.Build()
	File_internal_shell_parser_zu_zu_proto = out.File
	file_internal_shell_parser_zu_zu_proto_rawDesc = nil
	file_internal_shell_parser_zu_zu_proto_goTypes = nil
	file_internal_shell_parser_zu_zu_proto_depIdxs = nil
}
